services:
  tinyllama-api-cpu:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - MODEL_NAME=TinyLlama/TinyLlama-1.1B-Chat-v1.0
      - TRANSFORMERS_CACHE=/app/model_cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  tinyllama-api-gpu:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - PORT=8000
      - MODEL_NAME=TinyLlama/TinyLlama-1.1B-Chat-v1.0
      - TRANSFORMERS_CACHE=/app/model_cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped